<form class="form subscribe"
      novalidate
      action="<?php /* @escapeNotVerified */ echo $block->getFormActionUrl() ?>"
      method="post"
      data-mage-init='{"validation": {"errorClass": "mage-error"}}'
      id="newsletter-validate-detail-popup">
    <div class="field newsletter">
        <div class="control">
            <input name="email" type="email" id="newsletter"
                   placeholder="<?php /* @escapeNotVerified */ echo __('Enter your email address') ?>"
                   data-validate="{required:true, 'validate-email':true}"/>
        </div>
    </div>
    <div class="actions">
        <button class="action subscribe primary" title="<?php /* @escapeNotVerified */ echo __('Subscribe') ?>" type="submit">
            <span><?php /* @escapeNotVerified */ echo __('Subscribe') ?></span>
        </button>
    </div>
</form>