<?php
/**
 * Instagram Widget block template
 *
 * @var $block \Bitbull\InstagramWidget\Block\Instagram
 */
?>
<div style="display: none">
    <div class="popup-newsletter" data-mage-init='{"newsletterPopup": {"delay":"2"}}'>
        <div class="content">
            <h4>
                <?php /* @escapeNotVerified */ echo __('Subito per te uno sconto del ') ?>
                <span><?php /* @escapeNotVerified */ echo __('10%') ?></span>
            </h4>
            <form class="form subscribe"
                  novalidate
                  action="<?php /* @escapeNotVerified */ echo $block->getFormActionUrl() ?>"
                  method="post"
                  data-mage-init='{"validation": {"errorClass": "mage-error"}}'
                  id="newsletter-validate-detail">
                <div class="field newsletter">
                    <div class="control">
                        <input name="email" type="email" id="newsletter"
                               placeholder="<?php /* @escapeNotVerified */ echo __('Enter your email address') ?>"
                               data-validate="{required:true, 'validate-email':true}"/>
                    </div>
                </div>
                <div class="actions">
                    <button class="action subscribe primary" title="<?php /* @escapeNotVerified */ echo __('Subscribe') ?>" type="submit">
                        <span><?php /* @escapeNotVerified */ echo __('Subscribe') ?></span>
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>


