<?php
/**
 * Instagram Widget block template
 *
 * @var $block \Bitbull\InstagramWidget\Block\Instagram
 */
?>
<?php echo $block->getPopupText();?>
<div style="display: none">
    <div class="popup-newsletter">
        <div class="content">
            <?php echo $block->getPopupText();?>
            <?php echo $block->getChildHtml('newsletter-form'); ?>
        </div>
    </div>
</div>
<script type="text/x-magento-init">
    {
        ".popup-newsletter": {
            "newsletterPopup": <?php echo \Zend_Json::encode($block->getConfig()) ?>
        }
    }
</script>


